##### Copyright 2019 The TensorFlow Authors.

In [1]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Classify structured data with feature columns

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://www.tensorflow.org/tutorials/structured_data/feature_columns">
    <img src="https://www.tensorflow.org/images/tf_logo_32px.png" />
    View on TensorFlow.org</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/structured_data/feature_columns.ipynb">
    <img src="https://www.tensorflow.org/images/colab_logo_32px.png" />
    Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/tensorflow/docs/blob/master/site/en/tutorials/structured_data/feature_columns.ipynb">
    <img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />
    View source on GitHub</a>
  </td>
  <td>
    <a href="https://storage.googleapis.com/tensorflow_docs/docs/site/en/tutorials/structured_data/feature_columns.ipynb"><img src="https://www.tensorflow.org/images/download_logo_32px.png" />Download notebook</a>
  </td>
</table>

This tutorial demonstrates how to classify structured data (e.g. tabular data in a CSV). We will use [Keras](https://www.tensorflow.org/guide/keras) to define the model, and [feature columns](https://www.tensorflow.org/guide/feature_columns) as a bridge to map from columns in a CSV to features used to train the model. This tutorial contains complete code to:

* Load a CSV file using [Pandas](https://pandas.pydata.org/).
* Build an input pipeline to batch and shuffle the rows using [tf.data](https://www.tensorflow.org/guide/datasets).
* Map from columns in the CSV to features used to train the model using feature columns.
* Build, train, and evaluate a model using Keras.

## The Dataset

We will use a simplified version of the PetFinder [dataset](https://www.kaggle.com/c/petfinder-adoption-prediction). There are several thousand rows in the CSV. Each row describes a pet, and each column describes an attribute. We will use this information to predict the speed at which the pet will be adopted.

Following is a description of this dataset. Notice there are both numeric and categorical columns. There is a free text column which we will not use in this tutorial.

Column | Description| Feature Type | Data Type
------------|--------------------|----------------------|-----------------
Type | Type of animal (Dog, Cat) | Categorical | string
Age |  Age of the pet | Numerical | integer
Breed1 | Primary breed of the pet | Categorical | string
Color1 | Color 1 of pet | Categorical | string
Color2 | Color 2 of pet | Categorical | string
MaturitySize | Size at maturity | Categorical | string
FurLength | Fur length | Categorical | string
Vaccinated | Pet has been vaccinated | Categorical | string
Sterilized | Pet has been sterilized | Categorical | string
Health | Health Condition | Categorical | string
Fee | Adoption Fee | Numerical | integer
Description | Profile write-up for this pet | Text | string
PhotoAmt | Total uploaded photos for this pet | Numerical | integer
AdoptionSpeed | Speed of adoption | Classification | integer

## Import TensorFlow and other libraries

In [2]:
!pip install -q sklearn

In [3]:
import numpy as np
import pandas as pd

import tensorflow as tf

from tensorflow import feature_column
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

## Use Pandas to create a dataframe

[Pandas](https://pandas.pydata.org/) is a Python library with many helpful utilities for loading and working with structured data. We will use Pandas to download the dataset from a URL, and load it into a dataframe.

In [4]:
import pathlib

dataset_url = 'http://storage.googleapis.com/download.tensorflow.org/data/petfinder-mini.zip'
csv_file = 'datasets/petfinder-mini/petfinder-mini.csv'

tf.keras.utils.get_file('petfinder_mini.zip', dataset_url,
                        extract=True, cache_dir='.')
dataframe = pd.read_csv(csv_file)

   8192/1668792 [..............................] - ETA: 0s

1671168/1668792 [==============================] - 0s 0us/step


In [5]:
dataframe.head()

Type  Age                Breed1  Gender Color1    Color2 MaturitySize  \
0  Cat    3                 Tabby    Male  Black     White        Small   
1  Cat    1  Domestic Medium Hair    Male  Black     Brown       Medium   
2  Dog    1           Mixed Breed    Male  Brown     White       Medium   
3  Dog    4           Mixed Breed  Female  Black     Brown       Medium   
4  Dog    1           Mixed Breed    Male  Black  No Color       Medium   

  FurLength Vaccinated Sterilized   Health  Fee  \
0     Short         No         No  Healthy  100   
1    Medium   Not Sure   Not Sure  Healthy    0   
2    Medium        Yes         No  Healthy    0   
3     Short        Yes         No  Healthy  150   
4     Short         No         No  Healthy    0   

                                         Description  PhotoAmt  AdoptionSpeed  
0  Nibble is a 3+ month old ball of cuteness. He ...         1              2  
1  I just found it alone yesterday near my apartm...         2              0  
2  Their pregnant mother was dumped by her irresp...         7              3  
3  Good guard dog, very alert, active, obedience ...         8              2  
4  This handsome yet cute boy is up for adoption....         3              2

## Create target variable

The task in the original dataset is to predict the speed at which a pet will be adopted (e.g., in the first week, the first month, the first three months, and so on). Let's simplify this for our tutorial. Here, we will transform this into a binary classification problem, and simply predict whether the pet was adopted, or not.

After modifying the label column, 0 will indicate the pet was not adopted, and 1 will indicate it was.

In [6]:
# In the original dataset "4" indicates the pet was not adopted.
dataframe['target'] = np.where(dataframe['AdoptionSpeed']==4, 0, 1)

# Drop un-used columns.
dataframe = dataframe.drop(columns=['AdoptionSpeed', 'Description'])

## Split the dataframe into train, validation, and test

The dataset we downloaded was a single CSV file. We will split this into train, validation, and test sets.

In [7]:
train, test = train_test_split(dataframe, test_size=0.2)
train, val = train_test_split(train, test_size=0.2)
print(len(train), 'train examples')
print(len(val), 'validation examples')
print(len(test), 'test examples')

7383 train examples
1846 validation examples
2308 test examples


## Create an input pipeline using tf.data

Next, we will wrap the dataframes with [tf.data](https://www.tensorflow.org/guide/datasets). This will enable us  to use feature columns as a bridge to map from the columns in the Pandas dataframe to features used to train the model. If we were working with a very large CSV file (so large that it does not fit into memory), we would use tf.data to read it from disk directly. That is not covered in this tutorial.

In [8]:
# A utility method to create a tf.data dataset from a Pandas Dataframe
def df_to_dataset(dataframe, shuffle=True, batch_size=32):
  dataframe = dataframe.copy()
  labels = dataframe.pop('target')
  ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
  if shuffle:
    ds = ds.shuffle(buffer_size=len(dataframe))
  ds = ds.batch(batch_size)
  return ds

In [9]:
batch_size = 5 # A small batch sized is used for demonstration purposes
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

## Understand the input pipeline

Now that we have created the input pipeline, let's call it to see the format of the data it returns. We have used a small batch size to keep the output readable.

In [10]:
for feature_batch, label_batch in train_ds.take(1):
  print('Every feature:', list(feature_batch.keys()))
  print('A batch of ages:', feature_batch['Age'])
  print('A batch of targets:', label_batch )

Every feature: ['Type', 'Age', 'Breed1', 'Gender', 'Color1', 'Color2', 'MaturitySize', 'FurLength', 'Vaccinated', 'Sterilized', 'Health', 'Fee', 'PhotoAmt']
A batch of ages: tf.Tensor([ 2  4 48 36 15], shape=(5,), dtype=int64)
A batch of targets: tf.Tensor([0 1 0 1 1], shape=(5,), dtype=int64)


We can see that the dataset returns a dictionary of column names (from the dataframe) that map to column values from rows in the dataframe.

## Demonstrate several types of feature columns
TensorFlow provides many types of feature columns. In this section, we will create several types of feature columns, and demonstrate how they transform a column from the dataframe.

In [11]:
# We will use this batch to demonstrate several types of feature columns
example_batch = next(iter(train_ds))[0]

In [12]:
# A utility method to create a feature column
# and to transform a batch of data
def demo(feature_column):
  feature_layer = layers.DenseFeatures(feature_column)
  print(feature_layer(example_batch).numpy())

### Numeric columns
The output of a feature column becomes the input to the model (using the demo function defined above, we will be able to see exactly how each column from the dataframe is transformed). A [numeric column](https://www.tensorflow.org/api_docs/python/tf/feature_column/numeric_column) is the simplest type of column. It is used to represent real valued features. When using this column, your model will receive the column value from the dataframe unchanged.

In [13]:
photo_count = feature_column.numeric_column('PhotoAmt')
demo(photo_count)

[[5.]
 [1.]
 [8.]
 [1.]
 [4.]]


In the PetFinder dataset, most columns from the dataframe are categorical.

### Bucketized columns
Often, you don't want to feed a number directly into the model, but instead split its value into different categories based on numerical ranges. Consider raw data that represents a person's age. Instead of representing age as a numeric column, we could split the age into several buckets using a [bucketized column](https://www.tensorflow.org/api_docs/python/tf/feature_column/bucketized_column). Notice the one-hot values below describe which age range each row matches.

In [14]:
age = feature_column.numeric_column('Age')
age_buckets = feature_column.bucketized_column(age, boundaries=[1, 3, 5])
demo(age_buckets)

[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]


### Categorical columns
In this dataset, Type is represented as a string (e.g. 'Dog', or 'Cat'). We cannot feed strings directly to a model. Instead, we must first map them to numeric values. The categorical vocabulary columns provide a way to represent strings as a one-hot vector (much like you have seen above with age buckets). The vocabulary can be passed as a list using [categorical_column_with_vocabulary_list](https://www.tensorflow.org/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_list), or loaded from a file using [categorical_column_with_vocabulary_file](https://www.tensorflow.org/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file).

In [15]:
animal_type = feature_column.categorical_column_with_vocabulary_list(
      'Type', ['Cat', 'Dog'])

animal_type_one_hot = feature_column.indicator_column(animal_type)
demo(animal_type_one_hot)

[[1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]


### Embedding columns
Suppose instead of having just a few possible strings, we have thousands (or more) values per category. For a number of reasons, as the number of categories grow large, it becomes infeasible to train a neural network using one-hot encodings. We can use an embedding column to overcome this limitation. Instead of representing the data as a one-hot vector of many dimensions, an [embedding column](https://www.tensorflow.org/api_docs/python/tf/feature_column/embedding_column) represents that data as a lower-dimensional, dense vector in which each cell can contain any number, not just 0 or 1. The size of the embedding (8, in the example below) is a parameter that must be tuned.

Key point: using an embedding column is best when a categorical column has many possible values. We are using one here for demonstration purposes, so you have a complete example you can modify for a different dataset in the future.

In [16]:
# Notice the input to the embedding column is the categorical column
# we previously created
breed1 = feature_column.categorical_column_with_vocabulary_list(
      'Breed1', dataframe.Breed1.unique())
breed1_embedding = feature_column.embedding_column(breed1, dimension=8)
demo(breed1_embedding)

[[-0.02612482 -0.03677908 -0.23290709  0.09945397  0.08281118  0.36647838
  -0.17653757 -0.19444326]
 [ 0.30964506 -0.47443122 -0.41711554 -0.64884776 -0.21938232  0.4189953
  -0.44518548 -0.03063301]
 [ 0.30964506 -0.47443122 -0.41711554 -0.64884776 -0.21938232  0.4189953
  -0.44518548 -0.03063301]
 [-0.13033295  0.13335079 -0.25702646 -0.30840352  0.15335475  0.28056872
   0.13844194  0.3651677 ]
 [ 0.30964506 -0.47443122 -0.41711554 -0.64884776 -0.21938232  0.4189953
  -0.44518548 -0.03063301]]


### Hashed feature columns

Another way to represent a categorical column with a large number of values is to use a [categorical_column_with_hash_bucket](https://www.tensorflow.org/api_docs/python/tf/feature_column/categorical_column_with_hash_bucket). This feature column calculates a hash value of the input, then selects one of the `hash_bucket_size` buckets to encode a string. When using this column, you do not need to provide the vocabulary, and you can choose to make the number of hash_buckets significantly smaller than the number of actual categories to save space.

Key point: An important downside of this technique is that there may be collisions in which different strings are mapped to the same bucket. In practice, this can work well for some datasets regardless.

In [17]:
breed1_hashed = feature_column.categorical_column_with_hash_bucket(
      'Breed1', hash_bucket_size=10)
demo(feature_column.indicator_column(breed1_hashed))

[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


### Crossed feature columns
Combining features into a single feature, better known as [feature crosses](https://developers.google.com/machine-learning/glossary/#feature_cross), enables a model to learn separate weights for each combination of features. Here, we will create a new feature that is the cross of Age and Type. Note that `crossed_column` does not build the full table of all possible combinations (which could be very large). Instead, it is backed by a `hashed_column`, so you can choose how large the table is.

In [18]:
crossed_feature = feature_column.crossed_column([age_buckets, animal_type], hash_bucket_size=10)
demo(feature_column.indicator_column(crossed_feature))

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]


## Choose which columns to use
We have seen how to use several types of feature columns. Now we will use them to train a model. The goal of this tutorial is to show you the complete code (e.g. mechanics) needed to work with feature columns. We have selected a few columns to train our model below arbitrarily.

Key point: If your aim is to build an accurate model, try a larger dataset of your own, and think carefully about which features are the most meaningful to include, and how they should be represented.

In [19]:
feature_columns = []

# numeric cols
for header in ['PhotoAmt', 'Fee', 'Age']:
  feature_columns.append(feature_column.numeric_column(header))

In [20]:
# bucketized cols
age = feature_column.numeric_column('Age')
age_buckets = feature_column.bucketized_column(age, boundaries=[1, 2, 3, 4, 5])
feature_columns.append(age_buckets)

In [21]:
# indicator_columns
indicator_column_names = ['Type', 'Color1', 'Color2', 'Gender', 'MaturitySize',
                          'FurLength', 'Vaccinated', 'Sterilized', 'Health']
for col_name in indicator_column_names:
  categorical_column = feature_column.categorical_column_with_vocabulary_list(
      col_name, dataframe[col_name].unique())
  indicator_column = feature_column.indicator_column(categorical_column)
  feature_columns.append(indicator_column)

In [22]:
# embedding columns
breed1 = feature_column.categorical_column_with_vocabulary_list(
      'Breed1', dataframe.Breed1.unique())
breed1_embedding = feature_column.embedding_column(breed1, dimension=8)
feature_columns.append(breed1_embedding)

In [23]:
# crossed columns
age_type_feature = feature_column.crossed_column([age_buckets, animal_type], hash_bucket_size=100)
feature_columns.append(feature_column.indicator_column(age_type_feature))

### Create a feature layer
Now that we have defined our feature columns, we will use a [DenseFeatures](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/layers/DenseFeatures) layer to input them to our Keras model.

In [24]:
feature_layer = tf.keras.layers.DenseFeatures(feature_columns)

Earlier, we used a small batch size to demonstrate how feature columns worked. We create a new input pipeline with a larger batch size.

In [25]:
batch_size = 32
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

## Create, compile, and train the model

In [26]:
model = tf.keras.Sequential([
  feature_layer,
  layers.Dense(128, activation='relu'),
  layers.Dense(128, activation='relu'),
  layers.Dropout(.1),
  layers.Dense(1)
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])

model.fit(train_ds,
          validation_data=val_ds,
          epochs=10)

Epoch 1/10


  1/231 [..............................] - ETA: 0s - loss: 0.5957 - accuracy: 0.4375

  9/231 [>.............................] - ETA: 1s - loss: 0.7388 - accuracy: 0.4896

 18/231 [=>............................] - ETA: 1s - loss: 0.6749 - accuracy: 0.6076

 27/231 [==>...........................] - ETA: 1s - loss: 0.6638 - accuracy: 0.6377

 36/231 [===>..........................] - ETA: 1s - loss: 0.6951 - accuracy: 0.6441

 45/231 [====>.........................] - ETA: 1s - loss: 0.7244 - accuracy: 0.6576

 54/231 [======>.......................] - ETA: 1s - loss: 0.6997 - accuracy: 0.6603

 63/231 [=======>......................] - ETA: 0s - loss: 0.6963 - accuracy: 0.6652

 71/231 [========>.....................] - ETA: 0s - loss: 0.6899 - accuracy: 0.6620

 80/231 [=========>....................] - ETA: 0s - loss: 0.6853 - accuracy: 0.6621

 89/231 [==========>...................] - ETA: 0s - loss: 0.6760 - accuracy: 0.6629

 98/231 [===========>..................] - ETA: 0s - loss: 0.6684 - accuracy: 0.6722

107/231 [============>.................] - ETA: 0s - loss: 0.6587 - accuracy: 0.6764

116/231 [==============>...............] - ETA: 0s - loss: 0.6529 - accuracy: 0.6762

125/231 [===============>..............] - ETA: 0s - loss: 0.6455 - accuracy: 0.6775

133/231 [================>.............] - ETA: 0s - loss: 0.6469 - accuracy: 0.6776

142/231 [=================>............] - ETA: 0s - loss: 0.6406 - accuracy: 0.6780

151/231 [==================>...........] - ETA: 0s - loss: 0.6449 - accuracy: 0.6757

160/231 [===================>..........] - ETA: 0s - loss: 0.6506 - accuracy: 0.6750

169/231 [====================>.........] - ETA: 0s - loss: 0.6588 - accuracy: 0.6760

178/231 [======================>.......] - ETA: 0s - loss: 0.6575 - accuracy: 0.6743

187/231 [=======================>......] - ETA: 0s - loss: 0.6570 - accuracy: 0.6778

196/231 [========================>.....] - ETA: 0s - loss: 0.6545 - accuracy: 0.6767

205/231 [=========================>....] - ETA: 0s - loss: 0.6519 - accuracy: 0.6759

214/231 [==========================>...] - ETA: 0s - loss: 0.6476 - accuracy: 0.6783

223/231 [===========================>..] - ETA: 0s - loss: 0.6470 - accuracy: 0.6792

231/231 [==============================] - 2s 9ms/step - loss: 0.6442 - accuracy: 0.6783 - val_loss: 0.5172 - val_accuracy: 0.6907


Epoch 2/10
  1/231 [..............................] - ETA: 0s - loss: 0.4706 - accuracy: 0.7500

 10/231 [>.............................] - ETA: 1s - loss: 0.5087 - accuracy: 0.7437

 19/231 [=>............................] - ETA: 1s - loss: 0.5236 - accuracy: 0.7188

 28/231 [==>...........................] - ETA: 1s - loss: 0.5304 - accuracy: 0.7154

 37/231 [===>..........................] - ETA: 1s - loss: 0.5453 - accuracy: 0.7086

 46/231 [====>.........................] - ETA: 1s - loss: 0.5458 - accuracy: 0.7086

 55/231 [======>.......................] - ETA: 1s - loss: 0.5562 - accuracy: 0.7063

 64/231 [=======>......................] - ETA: 0s - loss: 0.5484 - accuracy: 0.7080

 73/231 [========>.....................] - ETA: 0s - loss: 0.5416 - accuracy: 0.7136

 82/231 [=========>....................] - ETA: 0s - loss: 0.5395 - accuracy: 0.7104

 91/231 [==========>...................] - ETA: 0s - loss: 0.5387 - accuracy: 0.7129

100/231 [===========>..................] - ETA: 0s - loss: 0.5424 - accuracy: 0.7122

109/231 [=============>................] - ETA: 0s - loss: 0.5419 - accuracy: 0.7139

118/231 [==============>...............] - ETA: 0s - loss: 0.5415 - accuracy: 0.7153

127/231 [===============>..............] - ETA: 0s - loss: 0.5450 - accuracy: 0.7099

136/231 [================>.............] - ETA: 0s - loss: 0.5470 - accuracy: 0.7089

145/231 [=================>............] - ETA: 0s - loss: 0.5416 - accuracy: 0.7121

154/231 [===================>..........] - ETA: 0s - loss: 0.5415 - accuracy: 0.7121

163/231 [====================>.........] - ETA: 0s - loss: 0.5400 - accuracy: 0.7126

172/231 [=====================>........] - ETA: 0s - loss: 0.5393 - accuracy: 0.7126

181/231 [======================>.......] - ETA: 0s - loss: 0.5405 - accuracy: 0.7125

190/231 [=======================>......] - ETA: 0s - loss: 0.5394 - accuracy: 0.7140

199/231 [========================>.....] - ETA: 0s - loss: 0.5405 - accuracy: 0.7122

208/231 [==========================>...] - ETA: 0s - loss: 0.5384 - accuracy: 0.7141

217/231 [===========================>..] - ETA: 0s - loss: 0.5397 - accuracy: 0.7150

226/231 [============================>.] - ETA: 0s - loss: 0.5391 - accuracy: 0.7171

231/231 [==============================] - 2s 7ms/step - loss: 0.5379 - accuracy: 0.7169 - val_loss: 0.5099 - val_accuracy: 0.7178


Epoch 3/10
  1/231 [..............................] - ETA: 0s - loss: 0.6610 - accuracy: 0.5938

 10/231 [>.............................] - ETA: 1s - loss: 0.4955 - accuracy: 0.7656

 19/231 [=>............................] - ETA: 1s - loss: 0.5343 - accuracy: 0.7434

 28/231 [==>...........................] - ETA: 1s - loss: 0.5269 - accuracy: 0.7388

 37/231 [===>..........................] - ETA: 1s - loss: 0.5160 - accuracy: 0.7432

 46/231 [====>.........................] - ETA: 1s - loss: 0.5021 - accuracy: 0.7473

 54/231 [======>.......................] - ETA: 1s - loss: 0.5086 - accuracy: 0.7431

 63/231 [=======>......................] - ETA: 1s - loss: 0.5065 - accuracy: 0.7455

 72/231 [========>.....................] - ETA: 0s - loss: 0.5126 - accuracy: 0.7400

 81/231 [=========>....................] - ETA: 0s - loss: 0.5097 - accuracy: 0.7392

 90/231 [==========>...................] - ETA: 0s - loss: 0.5099 - accuracy: 0.7420

 99/231 [===========>..................] - ETA: 0s - loss: 0.5052 - accuracy: 0.7434

107/231 [============>.................] - ETA: 0s - loss: 0.5041 - accuracy: 0.7471

116/231 [==============>...............] - ETA: 0s - loss: 0.5022 - accuracy: 0.7449

125/231 [===============>..............] - ETA: 0s - loss: 0.5080 - accuracy: 0.7415

134/231 [================>.............] - ETA: 0s - loss: 0.5122 - accuracy: 0.7393

143/231 [=================>............] - ETA: 0s - loss: 0.5152 - accuracy: 0.7356

152/231 [==================>...........] - ETA: 0s - loss: 0.5184 - accuracy: 0.7329

161/231 [===================>..........] - ETA: 0s - loss: 0.5180 - accuracy: 0.7314

170/231 [=====================>........] - ETA: 0s - loss: 0.5189 - accuracy: 0.7290

179/231 [======================>.......] - ETA: 0s - loss: 0.5183 - accuracy: 0.7294

188/231 [=======================>......] - ETA: 0s - loss: 0.5164 - accuracy: 0.7306

197/231 [========================>.....] - ETA: 0s - loss: 0.5169 - accuracy: 0.7278

206/231 [=========================>....] - ETA: 0s - loss: 0.5179 - accuracy: 0.7259

215/231 [==========================>...] - ETA: 0s - loss: 0.5196 - accuracy: 0.7251

224/231 [============================>.] - ETA: 0s - loss: 0.5176 - accuracy: 0.7253

231/231 [==============================] - 2s 7ms/step - loss: 0.5166 - accuracy: 0.7259 - val_loss: 0.4996 - val_accuracy: 0.7400


Epoch 4/10
  1/231 [..............................] - ETA: 0s - loss: 0.4136 - accuracy: 0.8125

 10/231 [>.............................] - ETA: 1s - loss: 0.5335 - accuracy: 0.7031

 19/231 [=>............................] - ETA: 1s - loss: 0.5078 - accuracy: 0.7204

 28/231 [==>...........................] - ETA: 1s - loss: 0.5001 - accuracy: 0.7444

 37/231 [===>..........................] - ETA: 1s - loss: 0.5037 - accuracy: 0.7306

 45/231 [====>.........................] - ETA: 1s - loss: 0.5050 - accuracy: 0.7257

 54/231 [======>.......................] - ETA: 1s - loss: 0.5095 - accuracy: 0.7269

 63/231 [=======>......................] - ETA: 0s - loss: 0.5162 - accuracy: 0.7252

 72/231 [========>.....................] - ETA: 0s - loss: 0.5122 - accuracy: 0.7231

 81/231 [=========>....................] - ETA: 0s - loss: 0.5067 - accuracy: 0.7261

 90/231 [==========>...................] - ETA: 0s - loss: 0.5069 - accuracy: 0.7299

 99/231 [===========>..................] - ETA: 0s - loss: 0.5062 - accuracy: 0.7317

108/231 [=============>................] - ETA: 0s - loss: 0.5025 - accuracy: 0.7318

116/231 [==============>...............] - ETA: 0s - loss: 0.5021 - accuracy: 0.7303

125/231 [===============>..............] - ETA: 0s - loss: 0.5013 - accuracy: 0.7325

134/231 [================>.............] - ETA: 0s - loss: 0.5004 - accuracy: 0.7330

143/231 [=================>............] - ETA: 0s - loss: 0.5005 - accuracy: 0.7323

152/231 [==================>...........] - ETA: 0s - loss: 0.5010 - accuracy: 0.7301

161/231 [===================>..........] - ETA: 0s - loss: 0.4999 - accuracy: 0.7302

170/231 [=====================>........] - ETA: 0s - loss: 0.5001 - accuracy: 0.7298

179/231 [======================>.......] - ETA: 0s - loss: 0.5006 - accuracy: 0.7308

188/231 [=======================>......] - ETA: 0s - loss: 0.5000 - accuracy: 0.7327

197/231 [========================>.....] - ETA: 0s - loss: 0.4998 - accuracy: 0.7321

206/231 [=========================>....] - ETA: 0s - loss: 0.5004 - accuracy: 0.7313

215/231 [==========================>...] - ETA: 0s - loss: 0.5018 - accuracy: 0.7318

224/231 [============================>.] - ETA: 0s - loss: 0.5020 - accuracy: 0.7321

231/231 [==============================] - 2s 7ms/step - loss: 0.5019 - accuracy: 0.7321 - val_loss: 0.5063 - val_accuracy: 0.6874


Epoch 5/10
  1/231 [..............................] - ETA: 0s - loss: 0.3777 - accuracy: 0.7812

 10/231 [>.............................] - ETA: 1s - loss: 0.4707 - accuracy: 0.7250

 19/231 [=>............................] - ETA: 1s - loss: 0.5006 - accuracy: 0.7270

 28/231 [==>...........................] - ETA: 1s - loss: 0.5009 - accuracy: 0.7355

 37/231 [===>..........................] - ETA: 1s - loss: 0.4971 - accuracy: 0.7297

 46/231 [====>.........................] - ETA: 1s - loss: 0.4956 - accuracy: 0.7323

 55/231 [======>.......................] - ETA: 1s - loss: 0.5047 - accuracy: 0.7307

 64/231 [=======>......................] - ETA: 0s - loss: 0.5063 - accuracy: 0.7310

 73/231 [========>.....................] - ETA: 0s - loss: 0.5056 - accuracy: 0.7307

 82/231 [=========>....................] - ETA: 0s - loss: 0.5088 - accuracy: 0.7313

 91/231 [==========>...................] - ETA: 0s - loss: 0.5046 - accuracy: 0.7308

100/231 [===========>..................] - ETA: 0s - loss: 0.5010 - accuracy: 0.7362

109/231 [=============>................] - ETA: 0s - loss: 0.5038 - accuracy: 0.7385

118/231 [==============>...............] - ETA: 0s - loss: 0.5030 - accuracy: 0.7362

127/231 [===============>..............] - ETA: 0s - loss: 0.5000 - accuracy: 0.7375

136/231 [================>.............] - ETA: 0s - loss: 0.5021 - accuracy: 0.7353

145/231 [=================>............] - ETA: 0s - loss: 0.5022 - accuracy: 0.7360

154/231 [===================>..........] - ETA: 0s - loss: 0.5027 - accuracy: 0.7370

163/231 [====================>.........] - ETA: 0s - loss: 0.4999 - accuracy: 0.7372

172/231 [=====================>........] - ETA: 0s - loss: 0.4973 - accuracy: 0.7376

179/231 [======================>.......] - ETA: 0s - loss: 0.4966 - accuracy: 0.7383

188/231 [=======================>......] - ETA: 0s - loss: 0.4945 - accuracy: 0.7404

197/231 [========================>.....] - ETA: 0s - loss: 0.4953 - accuracy: 0.7400

206/231 [=========================>....] - ETA: 0s - loss: 0.4952 - accuracy: 0.7391

215/231 [==========================>...] - ETA: 0s - loss: 0.4950 - accuracy: 0.7400

224/231 [============================>.] - ETA: 0s - loss: 0.4939 - accuracy: 0.7398

231/231 [==============================] - 2s 7ms/step - loss: 0.4930 - accuracy: 0.7408 - val_loss: 0.4937 - val_accuracy: 0.7324


Epoch 6/10
  1/231 [..............................] - ETA: 0s - loss: 0.6657 - accuracy: 0.6875

 10/231 [>.............................] - ETA: 1s - loss: 0.4950 - accuracy: 0.7094

 19/231 [=>............................] - ETA: 1s - loss: 0.4830 - accuracy: 0.7484

 28/231 [==>...........................] - ETA: 1s - loss: 0.4847 - accuracy: 0.7455

 37/231 [===>..........................] - ETA: 1s - loss: 0.4805 - accuracy: 0.7500

 46/231 [====>.........................] - ETA: 1s - loss: 0.4926 - accuracy: 0.7432

 55/231 [======>.......................] - ETA: 1s - loss: 0.4917 - accuracy: 0.7460

 64/231 [=======>......................] - ETA: 0s - loss: 0.4933 - accuracy: 0.7466

 73/231 [========>.....................] - ETA: 0s - loss: 0.4932 - accuracy: 0.7419

 82/231 [=========>....................] - ETA: 0s - loss: 0.4964 - accuracy: 0.7378

 91/231 [==========>...................] - ETA: 0s - loss: 0.4946 - accuracy: 0.7411

100/231 [===========>..................] - ETA: 0s - loss: 0.4956 - accuracy: 0.7403

110/231 [=============>................] - ETA: 0s - loss: 0.4926 - accuracy: 0.7418

119/231 [==============>...............] - ETA: 0s - loss: 0.4942 - accuracy: 0.7408

128/231 [===============>..............] - ETA: 0s - loss: 0.4922 - accuracy: 0.7417

137/231 [================>.............] - ETA: 0s - loss: 0.4938 - accuracy: 0.7413

146/231 [=================>............] - ETA: 0s - loss: 0.4931 - accuracy: 0.7417

155/231 [===================>..........] - ETA: 0s - loss: 0.4934 - accuracy: 0.7442

164/231 [====================>.........] - ETA: 0s - loss: 0.4944 - accuracy: 0.7409

173/231 [=====================>........] - ETA: 0s - loss: 0.4948 - accuracy: 0.7395

182/231 [======================>.......] - ETA: 0s - loss: 0.4938 - accuracy: 0.7421

191/231 [=======================>......] - ETA: 0s - loss: 0.4938 - accuracy: 0.7436

200/231 [========================>.....] - ETA: 0s - loss: 0.4928 - accuracy: 0.7439

209/231 [==========================>...] - ETA: 0s - loss: 0.4927 - accuracy: 0.7437

218/231 [===========================>..] - ETA: 0s - loss: 0.4922 - accuracy: 0.7428

227/231 [============================>.] - ETA: 0s - loss: 0.4921 - accuracy: 0.7422

231/231 [==============================] - 2s 7ms/step - loss: 0.4915 - accuracy: 0.7422 - val_loss: 0.4951 - val_accuracy: 0.7367


Epoch 7/10
  1/231 [..............................] - ETA: 0s - loss: 0.2954 - accuracy: 0.9062

 10/231 [>.............................] - ETA: 1s - loss: 0.4424 - accuracy: 0.8031

 19/231 [=>............................] - ETA: 1s - loss: 0.4505 - accuracy: 0.7812

 28/231 [==>...........................] - ETA: 1s - loss: 0.4584 - accuracy: 0.7824

 37/231 [===>..........................] - ETA: 1s - loss: 0.4676 - accuracy: 0.7762

 46/231 [====>.........................] - ETA: 1s - loss: 0.4713 - accuracy: 0.7704

 54/231 [======>.......................] - ETA: 1s - loss: 0.4757 - accuracy: 0.7656

 62/231 [=======>......................] - ETA: 1s - loss: 0.4746 - accuracy: 0.7651

 71/231 [========>.....................] - ETA: 0s - loss: 0.4702 - accuracy: 0.7667

 80/231 [=========>....................] - ETA: 0s - loss: 0.4683 - accuracy: 0.7672

 89/231 [==========>...................] - ETA: 0s - loss: 0.4700 - accuracy: 0.7669

 98/231 [===========>..................] - ETA: 0s - loss: 0.4749 - accuracy: 0.7592

107/231 [============>.................] - ETA: 0s - loss: 0.4764 - accuracy: 0.7605

116/231 [==============>...............] - ETA: 0s - loss: 0.4754 - accuracy: 0.7597

125/231 [===============>..............] - ETA: 0s - loss: 0.4744 - accuracy: 0.7615

134/231 [================>.............] - ETA: 0s - loss: 0.4730 - accuracy: 0.7610

143/231 [=================>............] - ETA: 0s - loss: 0.4752 - accuracy: 0.7592

152/231 [==================>...........] - ETA: 0s - loss: 0.4767 - accuracy: 0.7588

161/231 [===================>..........] - ETA: 0s - loss: 0.4758 - accuracy: 0.7597

170/231 [=====================>........] - ETA: 0s - loss: 0.4759 - accuracy: 0.7605

179/231 [======================>.......] - ETA: 0s - loss: 0.4758 - accuracy: 0.7608

188/231 [=======================>......] - ETA: 0s - loss: 0.4763 - accuracy: 0.7601

197/231 [========================>.....] - ETA: 0s - loss: 0.4788 - accuracy: 0.7582

206/231 [=========================>....] - ETA: 0s - loss: 0.4809 - accuracy: 0.7561

215/231 [==========================>...] - ETA: 0s - loss: 0.4820 - accuracy: 0.7536

224/231 [============================>.] - ETA: 0s - loss: 0.4835 - accuracy: 0.7527

231/231 [==============================] - 2s 7ms/step - loss: 0.4841 - accuracy: 0.7520 - val_loss: 0.4984 - val_accuracy: 0.7129


Epoch 8/10
  1/231 [..............................] - ETA: 0s - loss: 0.4531 - accuracy: 0.6875

 10/231 [>.............................] - ETA: 1s - loss: 0.4720 - accuracy: 0.7406

 19/231 [=>............................] - ETA: 1s - loss: 0.4413 - accuracy: 0.7730

 28/231 [==>...........................] - ETA: 1s - loss: 0.4683 - accuracy: 0.7589

 37/231 [===>..........................] - ETA: 1s - loss: 0.4727 - accuracy: 0.7576

 46/231 [====>.........................] - ETA: 1s - loss: 0.4772 - accuracy: 0.7514

 55/231 [======>.......................] - ETA: 1s - loss: 0.4774 - accuracy: 0.7545

 64/231 [=======>......................] - ETA: 0s - loss: 0.4811 - accuracy: 0.7500

 73/231 [========>.....................] - ETA: 0s - loss: 0.4827 - accuracy: 0.7453

 82/231 [=========>....................] - ETA: 0s - loss: 0.4851 - accuracy: 0.7454

 91/231 [==========>...................] - ETA: 0s - loss: 0.4833 - accuracy: 0.7466

100/231 [===========>..................] - ETA: 0s - loss: 0.4825 - accuracy: 0.7478

109/231 [=============>................] - ETA: 0s - loss: 0.4794 - accuracy: 0.7489

118/231 [==============>...............] - ETA: 0s - loss: 0.4740 - accuracy: 0.7545

127/231 [===============>..............] - ETA: 0s - loss: 0.4728 - accuracy: 0.7576

136/231 [================>.............] - ETA: 0s - loss: 0.4696 - accuracy: 0.7594

145/231 [=================>............] - ETA: 0s - loss: 0.4711 - accuracy: 0.7586

154/231 [===================>..........] - ETA: 0s - loss: 0.4727 - accuracy: 0.7579

163/231 [====================>.........] - ETA: 0s - loss: 0.4733 - accuracy: 0.7582

172/231 [=====================>........] - ETA: 0s - loss: 0.4742 - accuracy: 0.7567

181/231 [======================>.......] - ETA: 0s - loss: 0.4752 - accuracy: 0.7571

190/231 [=======================>......] - ETA: 0s - loss: 0.4760 - accuracy: 0.7558

199/231 [========================>.....] - ETA: 0s - loss: 0.4781 - accuracy: 0.7541

208/231 [==========================>...] - ETA: 0s - loss: 0.4790 - accuracy: 0.7541

217/231 [===========================>..] - ETA: 0s - loss: 0.4797 - accuracy: 0.7514

226/231 [============================>.] - ETA: 0s - loss: 0.4782 - accuracy: 0.7529

231/231 [==============================] - 2s 7ms/step - loss: 0.4788 - accuracy: 0.7534 - val_loss: 0.4919 - val_accuracy: 0.7291


Epoch 9/10
  1/231 [..............................] - ETA: 0s - loss: 0.4007 - accuracy: 0.8125

 10/231 [>.............................] - ETA: 1s - loss: 0.4711 - accuracy: 0.7469

 19/231 [=>............................] - ETA: 1s - loss: 0.4563 - accuracy: 0.7467

 28/231 [==>...........................] - ETA: 1s - loss: 0.4764 - accuracy: 0.7533

 37/231 [===>..........................] - ETA: 1s - loss: 0.4802 - accuracy: 0.7517

 46/231 [====>.........................] - ETA: 1s - loss: 0.4792 - accuracy: 0.7527

 55/231 [======>.......................] - ETA: 1s - loss: 0.4756 - accuracy: 0.7534

 64/231 [=======>......................] - ETA: 0s - loss: 0.4716 - accuracy: 0.7563

 73/231 [========>.....................] - ETA: 0s - loss: 0.4748 - accuracy: 0.7564

 79/231 [=========>....................] - ETA: 0s - loss: 0.4784 - accuracy: 0.7532

 87/231 [==========>...................] - ETA: 0s - loss: 0.4827 - accuracy: 0.7493

 96/231 [===========>..................] - ETA: 0s - loss: 0.4867 - accuracy: 0.7428

105/231 [============>.................] - ETA: 0s - loss: 0.4859 - accuracy: 0.7417

114/231 [=============>................] - ETA: 0s - loss: 0.4870 - accuracy: 0.7440

123/231 [==============>...............] - ETA: 0s - loss: 0.4843 - accuracy: 0.7431

132/231 [================>.............] - ETA: 0s - loss: 0.4800 - accuracy: 0.7472

141/231 [=================>............] - ETA: 0s - loss: 0.4814 - accuracy: 0.7465

150/231 [==================>...........] - ETA: 0s - loss: 0.4830 - accuracy: 0.7444

159/231 [===================>..........] - ETA: 0s - loss: 0.4807 - accuracy: 0.7445

168/231 [====================>.........] - ETA: 0s - loss: 0.4818 - accuracy: 0.7440

177/231 [=====================>........] - ETA: 0s - loss: 0.4786 - accuracy: 0.7463

186/231 [=======================>......] - ETA: 0s - loss: 0.4762 - accuracy: 0.7471

195/231 [========================>.....] - ETA: 0s - loss: 0.4764 - accuracy: 0.7473

204/231 [=========================>....] - ETA: 0s - loss: 0.4748 - accuracy: 0.7483

213/231 [==========================>...] - ETA: 0s - loss: 0.4771 - accuracy: 0.7475

222/231 [===========================>..] - ETA: 0s - loss: 0.4775 - accuracy: 0.7475

231/231 [==============================] - ETA: 0s - loss: 0.4751 - accuracy: 0.7475

231/231 [==============================] - 2s 7ms/step - loss: 0.4751 - accuracy: 0.7475 - val_loss: 0.4955 - val_accuracy: 0.7254


Epoch 10/10
  1/231 [..............................] - ETA: 0s - loss: 0.5184 - accuracy: 0.7500

 10/231 [>.............................] - ETA: 1s - loss: 0.4610 - accuracy: 0.7531

 19/231 [=>............................] - ETA: 1s - loss: 0.4424 - accuracy: 0.7829

 28/231 [==>...........................] - ETA: 1s - loss: 0.4591 - accuracy: 0.7667

 37/231 [===>..........................] - ETA: 1s - loss: 0.4565 - accuracy: 0.7610

 46/231 [====>.........................] - ETA: 1s - loss: 0.4691 - accuracy: 0.7548

 55/231 [======>.......................] - ETA: 1s - loss: 0.4756 - accuracy: 0.7523

 64/231 [=======>......................] - ETA: 0s - loss: 0.4706 - accuracy: 0.7549

 73/231 [========>.....................] - ETA: 0s - loss: 0.4700 - accuracy: 0.7586

 82/231 [=========>....................] - ETA: 0s - loss: 0.4696 - accuracy: 0.7603

 91/231 [==========>...................] - ETA: 0s - loss: 0.4715 - accuracy: 0.7558

100/231 [===========>..................] - ETA: 0s - loss: 0.4734 - accuracy: 0.7538

109/231 [=============>................] - ETA: 0s - loss: 0.4699 - accuracy: 0.7546

118/231 [==============>...............] - ETA: 0s - loss: 0.4701 - accuracy: 0.7542

127/231 [===============>..............] - ETA: 0s - loss: 0.4684 - accuracy: 0.7554

136/231 [================>.............] - ETA: 0s - loss: 0.4683 - accuracy: 0.7557

145/231 [=================>............] - ETA: 0s - loss: 0.4676 - accuracy: 0.7558

150/231 [==================>...........] - ETA: 0s - loss: 0.4693 - accuracy: 0.7550

158/231 [===================>..........] - ETA: 0s - loss: 0.4705 - accuracy: 0.7551

167/231 [====================>.........] - ETA: 0s - loss: 0.4717 - accuracy: 0.7552

176/231 [=====================>........] - ETA: 0s - loss: 0.4718 - accuracy: 0.7537

185/231 [=======================>......] - ETA: 0s - loss: 0.4747 - accuracy: 0.7535

194/231 [========================>.....] - ETA: 0s - loss: 0.4748 - accuracy: 0.7526

203/231 [=========================>....] - ETA: 0s - loss: 0.4739 - accuracy: 0.7535

212/231 [==========================>...] - ETA: 0s - loss: 0.4706 - accuracy: 0.7562

221/231 [===========================>..] - ETA: 0s - loss: 0.4694 - accuracy: 0.7585

230/231 [============================>.] - ETA: 0s - loss: 0.4702 - accuracy: 0.7565

231/231 [==============================] - 2s 7ms/step - loss: 0.4699 - accuracy: 0.7565 - val_loss: 0.5118 - val_accuracy: 0.6896


In [27]:
loss, accuracy = model.evaluate(test_ds)
print("Accuracy", accuracy)

 1/73 [..............................] - ETA: 0s - loss: 0.4602 - accuracy: 0.7500

12/73 [===>..........................] - ETA: 0s - loss: 0.5140 - accuracy: 0.6719

23/73 [========>.....................] - ETA: 0s - loss: 0.5240 - accuracy: 0.6929

34/73 [============>.................] - ETA: 0s - loss: 0.5358 - accuracy: 0.6893

44/73 [=================>............] - ETA: 0s - loss: 0.5300 - accuracy: 0.6967

54/73 [=====================>........] - ETA: 0s - loss: 0.5313 - accuracy: 0.6927

64/73 [=========================>....] - ETA: 0s - loss: 0.5244 - accuracy: 0.6948

73/73 [==============================] - 0s 5ms/step - loss: 0.5202 - accuracy: 0.7002


Accuracy 0.7001733183860779


Key point: You will typically see best results with deep learning with much larger and more complex datasets. When working with a small dataset like this one, we recommend using a decision tree or random forest as a strong baseline. The goal of this tutorial is not to train an accurate model, but to demonstrate the mechanics of working with structured data, so you have code to use as a starting point when working with your own datasets in the future.

## Next steps
The best way to learn more about classifying structured data is to try it yourself. We suggest finding another dataset to work with, and training a model to classify it using code similar to the above. To improve accuracy, think carefully about which features to include in your model, and how they should be represented.